# Generated by Django 4.2.11 on 2024-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='to_user',
            field=models.IntegerField(default=22),
        ),
    ]
