# Generated by Django 4.2.11 on 2024-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_share_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='to_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='short',
            name='content',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='shorts\\media\\short'),
        ),
    ]
