# Generated by Django 4.2.11 on 2024-08-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0004_alter_share_to_user_alter_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='short',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_short', to='shorts.short'),
        ),
    ]
